Release 0.2.0
aicers/giganto pull request #116
Opened 2022-09-30 02:30 UTC by kimhanbeom

Closes: #112

2022-09-30 04:00 UTC, kimhanbeom commented
0.2.0에 해당되는 기능의 버그 이슈로 release를 보류합니다.

2022-09-30 19:12 UTC, msk requested changes

2022-09-30 19:12 UTC, msk commented on CHANGELOG.md
>  ## [Unreleased]
릴리스할 때는 이 `Unreleased` 항목은 지워주시고, 파일 끝에 아래처럼 0.1.0과 0.2.0의 diff 보여주는 링크 추가해주세요.

```text
[0.2.0]: https://github.com/aicers/giganto/compare/0.1.0...0.2.0
[0.1.0]: https://github.com/aicers/giganto/tree/0.1.0
```

2022-10-04 01:16 UTC, kimhanbeom commented
해당 사항 수정 완료 했습니다.

2022-10-04 01:17 UTC, msk approved these changes

2022-10-04 01:38 UTC, merged