Add publish protocol logic
aicers/giganto pull request #135
Opened 2022-10-12 04:08 UTC by kimhanbeom

- Add Requst/Response log message logic
- Add handshake logic

Closes: #126, Closes: #132

2022-10-12 19:05 UTC, msk requested changes
1. publish API는 reconverge나 hog에서 분석에 필요한 만큼 데이터를 가져가도록 하는 거라서 `MAXIMUM_PAGE_SIZE`와 같이 한 화면에 보여주는 개수 제한은 하지 않는 것이 좋겠습니다.
2. CHANGELOG도 업데이트해 주세요.

2022-10-13 00:21 UTC, kimhanbeom commented
해당 사항 수정 완료했습니다.

2022-10-13 01:30 UTC, msk commented
#134 머지 후 생긴 conflict 해결해주세요.

2022-10-13 01:35 UTC, kimhanbeom commented
conflict 해결했습니다.

2022-10-13 01:35 UTC, msk approved these changes

2022-10-13 02:01 UTC, merged