Reconstruct separating the filter structure
aicers/giganto pull request #139
Opened 2022-10-13 04:38 UTC by kimhanbeom

Closes: #137

2022-10-13 17:47 UTC, msk requested changes

2022-10-13 17:47 UTC, msk commented on src/graphql.rs
> +pub struct LogFilter {
각 필터는 해당 모듈(`LogFilter`는 log 모듈, `NetworkFilter`는 network 모듈)로 옮기는 것이 좋겠습니다.

2022-10-13 17:47 UTC, msk commented on src/graphql.rs
>      fn check(
가독성 차원에서 함수 정의 사이에 빈 줄 하나 넣어주세요.

2022-10-14 00:13 UTC, kimhanbeom commented
해당 사항 수정 완료 했습니다.

2022-10-14 01:16 UTC, msk approved these changes

2022-10-14 01:16 UTC, merged