Add GraphQL Interface
aicers/giganto pull request #16
Opened 2022-08-19 08:22 UTC by BLYKIM

Add graphql/playground
Change Key, Cert file to PEM file for tls

Close #15

2022-08-19 18:17 UTC, msk requested changes

2022-08-19 18:17 UTC, msk commented on src/settings.rs
> +        let cert_path = path.join("cert.crt");
PEM 포맷 파일 확장자는 .pem으로 해 주세요.

2022-08-19 18:17 UTC, msk commented on src/settings.rs
> +const LOCAL_GRAPHQL_ADDRESS: &str = "127.0.0.1:8443";
윗 줄의 ingestion address처럼 이것도 `DEFAULT_GRAPHQL_ADDRESS`라고 하는 것이 좋겠습니다. "LOCAL"이라고 하면 "REMOTE"와 상대되는 개념으로 쓰여서, 디폴트 값인지 아닌지와 관계없이 보통 내 쪽의 소켓 주소를 의미합니다.

2022-08-22 02:30 UTC, msk commented
@kimhanbeom, README에 tests/ingestion.rs의 테스트 돌려보는 방법(giganto 실행 포함) 좀 적어주세요.
@BLYKIM tests/ingestion.rs의 테스트가 이 브랜치에서도 잘 동작하는지 확인 부탁드립니다.

2022-08-22 03:12 UTC, kimhanbeom commented
@msk 
현재 진행중인 이슈에서 작성하겠습니다.

2022-08-22 17:34 UTC, msk requested changes

2022-08-22 17:34 UTC, msk commented on src/ingestion.rs
> +            bail!("failed to read (cert, key) file, \n$HOME/Library/Application Support/com.einsis.giganto/('key.pem', 'cert.pem') or config file error ");
파일 경로는 시스템 타입(macOS, Linux 등)이나 설정 내용에 따라 다를 수 있으므로 메시지에 하드코딩하면 안 됩니다. 경로를 출력하려면 실제로 사용한 경로(`cert_path`나 `key_path`)를 출력해주세요.

2022-08-22 23:49 UTC, msk approved these changes

2022-08-22 23:49 UTC, merged