Receives and query for SMTP events
aicers/giganto pull request #171
Opened 2022-11-11 10:09 UTC by syncpark

- Receives SMTP events from Piglet
- Enables to query for SMTP events
- Adds `answer` field to DNS event
- Change `status` field of HTTP event

2022-11-14 22:46 UTC, msk requested changes
하위 호환성이 깨지는 변경 사항이므로 Cargo.toml에서 버전을 0.5.0-alpha.1으로 올려주세요. (알파 버전은 태그는 하지 않습니다).

2022-11-14 22:46 UTC, msk commented on src/graphql/network.rs
> +    status: String,
이건 `String`으로 바꾸면 유리한 점이 어떤 건가요?

2022-11-14 22:46 UTC, msk commented on CHANGELOG.md
> +- Adds `smtp`  to receive and save SMTP event.
`to` 앞에 공백이 두 개 있습니다.

2022-11-15 04:02 UTC, syncpark commented on src/graphql/network.rs
> +    status: String,
@msk Piglet에서 status 정보를 String으로 생성됩니다. 이 값이 u16으로 변환했을때 문제가 발생할 가능성도 있어서 그대로 유지하려고 합니다.

2022-11-15 04:44 UTC, syncpark commented on CHANGELOG.md
> +- Adds `smtp`  to receive and save SMTP event.
수정했습니다.

2022-11-15 17:55 UTC, msk commented on src/graphql/network.rs
> +    answer: String,
이건 원래 `Vec`이니까 GraphQL에서도 `[String!]!`으로 하는 것이 낫지 않을까요?

2022-11-15 17:55 UTC, msk commented on src/graphql/network.rs
> +    status: String,
그럼 생성 부분을 고쳐서 `status_code`를 제대로 읽도록 하는게 맞을 것 같은데요. Zeek의 경우도 `status_code`를 정수로 취급하고 있습니다.

2022-11-16 02:12 UTC, syncpark commented on src/graphql/network.rs
> +    answer: String,
수정했습니다.

2022-11-16 02:13 UTC, syncpark commented
Piglet에서 HTTP status를 u16으로 수정하고, Giganto도 원래 코드를 사용하도록 수정했습니다.

2022-11-16 04:40 UTC, msk commented
> Piglet에서 HTTP status를 u16으로 수정하고, Giganto도 원래 코드를 사용하도록 수정했습니다.

CHANGELOG도 업데이트해주세요.

2022-11-16 05:01 UTC, msk approved these changes

2022-11-16 05:16 UTC, merged