Add statistics processing function
aicers/giganto pull request #236
Opened 2023-01-09 08:01 UTC by kimhanbeom

- Add `analyzer statistics` column family
- Generate and save giganto's raw data statistics
- Modify `statistics` column family name to `collector statistics`
- Add `request collector statistics` and `request analyzer statistics` to Graphql API.

Closes: #219

2023-01-09 20:30 UTC, msk commented on src/graphql.rs
> +    key_prefix: Option<&[u8]>,
`key_prefix`가 `Some("")`인 것과 `None`은 다른가요?

2023-01-10 01:24 UTC, kimhanbeom commented on src/graphql.rs
> +    key_prefix: Option<&[u8]>,
@msk 
이번에 생성한 `analyzer statistics column family` 의 경우 db의 key 값으로 timestamp만 사용하도록 되어 있습니다. 
그렇기 때문에 key_prefix가 `Some`인 경우에는 기존 column family의 source+timestamp 형태의 key생성을 하고 , `None`인 경우는 timestamp만 key로 생성하도록 하고 있습니다.

2023-01-10 01:36 UTC, kimhanbeom commented on src/graphql.rs
> +    key_prefix: Option<&[u8]>,
@msk 
get_connection을 호출하는 부분은 전부 key를 souce+timestamp로 사용하고 있어서, 실제로 key를 생성하는 함수인 `upper_open_bound_key` `upper_closed_bound_key` `lower_closed_bound_key`를 호출하는 부분쪽에서 직접 Option을 사용할 수 있도록 변경하겠습니다.

2023-01-10 04:36 UTC, syncpark requested changes

2023-01-10 04:36 UTC, syncpark commented on src/ingestion.rs
> +                println!("{stats_result:#?}");
Debug 코드 같은데 삭제해야하지 않을까요?

2023-01-10 04:36 UTC, syncpark commented on src/settings.rs
> +        .set_default("statistics_period", "1h")
statistics period 기본값이 1 hour는 너무 깁니다. 600초(10분) 정도가 적당할 듯 합니다.

2023-01-10 04:36 UTC, syncpark commented on src/graphql/statistics.rs
> +        ctx: &Context<'ctx>,
통계 데이터는 그 값을 읽어서 화면 표시용도로 사용하는게 아니라 대시보드나 상태 창에 차트를 그리거나 합계, 평균을 계산하는 용도로 사용합니다.
그런데 GraphQL API에서 after, before 등의 파라미터는 화면 표시하기 위한, 특히 페이징을 위한 데이터 조회 용도로 사용하지 않나요? 이 부분은 사장님과 얘기해보고 수정할 필요가 있습니다.

2023-04-03 04:42 UTC, kimhanbeom commented
해당 기능은 main으로 merge되지 않고 필요에 따라 branch로만 관리될 예정이므로 close하겠습니다.

2023-04-03 04:42 UTC, closed without merging