Add more dns field
aicers/giganto pull request #241
Opened 2023-01-10 01:14 UTC by BLYKIM

Close:#235

2023-01-10 04:12 UTC, syncpark requested changes

2023-01-10 04:12 UTC, syncpark commented on src/ingestion/network.rs
> +            self.ttl,
TTL 값은 Answer 필드값처럼 Comma separated string으로 변환해주세요.
벡터 값을 Debug 문자열로 출력하면 그 이벤트를 읽어서 사용하는 코드에서 추가 작업이 필요하게 됩니다.

2023-01-10 04:12 UTC, syncpark commented on src/ingestion/network.rs
> +            self.qtype,
qclass, qtype 값은 문자열로 출력해주세요. 문자열로 변환이 안될 경우에만 숫자로 출력하면 됩니다.

예: q`class == 1` => `C_INTERNET`, `qtype == 1` => `A`

2023-01-11 00:33 UTC, msk approved these changes

2023-01-11 02:31 UTC, syncpark approved these changes

2023-01-11 02:31 UTC, merged