Send data to server
aicers/giganto pull request #3
Opened 2022-08-16 01:12 UTC by kimhanbeom

Resolves: #2

2022-08-18 18:57 UTC, msk requested changes

2022-08-18 18:57 UTC, msk commented on Cargo.toml
> +url = "2"
테스트에서만 쓰이는 crate는 `[dependeicies]` 섹션이 아니라 `[dev-dependencies]` 섹션에 들어갑니다.

2022-08-18 18:57 UTC, msk commented on tests/common.rs
> +    client_crypto.alpn_protocols = vec![ALPN_PROTOCOLS.into()];
이건 왜 필요한가요?

2022-08-18 18:57 UTC, msk commented on tests/common.rs
> +    let dir = ProjectDirs::from(QUALIFIER, ORGANIZATION, PKG_NAME)
테스트는 최대한 자동화하고 사람이 하는 일은 최소로 해야 합니다. 그런 점에서 테스트를 돌리는 사람이 config directory에 인증서를 만들어 넣게 하는 것 보다는, tests/ 디렉터리에 미리 생성한 인증서와 키 파일을 넣어 놓고(`git add`) 테스트 프로그램에서는 그걸 읽어 쓰도록 하는 것이 좋습니다.

2022-08-18 23:49 UTC, kimhanbeom commented on tests/common.rs
> +    client_crypto.alpn_protocols = vec![ALPN_PROTOCOLS.into()];
@msk 
server의  alpn_protocol과 맞추기 위해서 사용하였습니다.
저희는 http를 사용하지 않으니까 이 부분은 server/test 전부 뺴면 되는건가요?

2022-08-18 23:50 UTC, msk commented on tests/common.rs
> +    client_crypto.alpn_protocols = vec![ALPN_PROTOCOLS.into()];
그렇습니다.

2022-08-18 23:51 UTC, kimhanbeom commented on tests/common.rs
> +    client_crypto.alpn_protocols = vec![ALPN_PROTOCOLS.into()];
네 수정하겠습니다.

2022-08-18 23:59 UTC, kimhanbeom commented
해당 사항 수정 완료했습니다.

2022-08-19 00:28 UTC, msk approved these changes

2022-08-19 00:41 UTC, merged