Changed to return the path to the config file from the setting module
aicers/giganto pull request #381
Opened 2023-05-03 02:36 UTC by kimhanbeom

현장에서 giganto의 설정파일은 `usr/local/aice/conf/giganto.toml` 의 위치로 고정되어 있습니다.
이에 맞춰 개발시에 argument를 줄 경우 argument의 path를 , 현장에서처럼 argument없이 실행할 경우 고정된 path를 읽어서 저장하고, graphql 을 통해 config 재설정 및 reboot을 할때 해당 path를 이용하도록 수정하였습니다.

2023-05-03 07:32 UTC, syncpark approved these changes

2023-05-03 07:32 UTC, syncpark commented on README.md
> +* `usr/local/aice/conf/giganto.toml`
`/usr/local/aice/conf/giganto.toml`입니다. 앞에 `/`를 추가해주세요.

2023-05-03 07:32 UTC, syncpark commented on README.md
>  By default, giganto reads the config file from the following directories:
이젠 directories 대신 path가 되겠네요.

2023-05-03 08:44 UTC, syncpark approved these changes

2023-05-03 17:30 UTC, msk commented
> 기존의 setting은 argument의 설정이나 default 설정을 이용하도록 되어 있습니다. 그러나 실제 현재 현장에서 사용 되는 default 설정은 아래와 같습니다.

현장에서 사용하는 값은 deploy하는 환경에 따라서 바뀔 수도 있는 값이므로, 그걸 소스에 하드코딩하는 것은 바람직하지 않습니다. 오히려 현장에서 쓰는 값은 디폴트에 의존하는 걸 최대한 피하고, 모두 명시적으로 쓰도록 해야 현장에서 설치하는 사람이 디폴트가 뭔지 확인해야 하는 등의 수고를 줄일 수 있습니다.

> 또한 graphql 의 `setGigantoConfig` 및 `reboot`을 할때 읽는 설정 파일의 위치는 고정값을 항상 사용하기 때문에, 만일 argument를 통해 giganto를 실행한 경우에는 실제 config 파일을 재 설정하지 않을 것입니다.

이건 `setGigantoConfig`나 `reboot`의 구현을 고쳐야 할 문제로 보입니다. 하드코딩된 위치를 설정 파일의 위치로 쓰면 안 되고, 처음 giganto를 구동할 때 썼던 설정 파일을 쓰도록 해야 할 것 같은데요.

2023-05-04 02:21 UTC, syncpark commented
### 디폴트 설정 이슈
운영, 유지보수 작업의 편의를 위해서는 오히려 디폴트를 사용하도록 권장하고, 혹은 설득하는게 맞지 않을까요?

유지보수 담당 엔지니어들이 다수의 고객 사이트를 담당하는데 각기 다른 설정 값을 사용하면 실수할 가능성이 높아집니다. 그래서 가급적이면 디폴트 값을 사용하도록 권장하고, 실제 설치도 그렇게 진행하고 있습니다.
유지보수 계약으로 엔지니어들이 모두 우리 직원이기때문에 작업과 관리의 편의성이 우선일 수 밖에 없습니다.

당연히 고객별 요구 환경이 다를 수 있기때문에 직접 지정할 수 있는 방법도 지원할 필요는 있습니다.

그래서 현재 운영 방향은 이렇습니다.
1. 디폴트 값을 사용하도록 패키지를 설치하거나 권장한다. 
2. 디폴트를 적용하기 불가능한 상황에서만 다른 설정 값을 사용하도록 허용한다.

이번 수정도 여기에 맞춘 내용입니다.

### 두번째 이슈
설정 파일의 위치는 디폴트 위치와 사용자 정의 위치의 2종류입니다.

원격 설정할 때는 현재 사용중인 설정 파일 경로에 수정된 내용을 저장해야 하기 때문에 프로그램 시작할 때의 설정 파일 경로를 가지고 다니도록 수정한 내용입니다.

2023-05-04 17:37 UTC, msk commented
> ### 디폴트 설정 이슈
> 운영, 유지보수 작업의 편의를 위해서는 오히려 디폴트를 사용하도록 권장하고, 혹은 설득하는게 맞지 않을까요?
> 
> 유지보수 담당 엔지니어들이 다수의 고객 사이트를 담당하는데 각기 다른 설정 값을 사용하면 실수할 가능성이 높아집니다. 그래서 가급적이면 디폴트 값을 사용하도록 권장하고, 실제 설치도 그렇게 진행하고 있습니다. 유지보수 계약으로 엔지니어들이 모두 우리 직원이기때문에 작업과 관리의 편의성이 우선일 수 밖에 없습니다.
> 
> 당연히 고객별 요구 환경이 다를 수 있기때문에 직접 지정할 수 있는 방법도 지원할 필요는 있습니다.
> 
> 그래서 현재 운영 방향은 이렇습니다.
> 
> 1. 디폴트 값을 사용하도록 패키지를 설치하거나 권장한다.
> 2. 디폴트를 적용하기 불가능한 상황에서만 다른 설정 값을 사용하도록 허용한다.

유지보수 엔지니어들의 편의성을 고려하는 것이 중요한 목표라는 점에 동의합니다. 하지만, 하드코딩된 경로를 사용하는 것 보다는 소프트웨어를 일반적인 용도를 가정하고 만드는 것이 장기적으로 더 바람직한 방향이라고 생각합니다. 그 이유는 다음과 같습니다.

첫째, 지금은 유지보수 엔지니어와 개발자들이 밀접하게 일하고 있기 때문에 현장에서 필요한 값들을 디폴트로 책정하는 것이 별 어려움이 없고 유지보수 엔지니어들의 부담을 덜어줄 수 있으나, 향후 고객이 증가하면 현장의 요구사항도 다양해질 수 있고, 디폴트값이 변경될 수도 있습니다. 예를 들어 `/usr/local/aice`만 해도 제품 상표(AICE)만 바뀌어도 수정해야 하는 경로입니다. 이런 마케팅 요구사항, 고객의 요구사항이 바뀔 때마다 개발자들에게 요청이 들어가는 것은 불필요하다고 봅니다. 개발자들은 가급적 저런 요구사항과 관계없이 표준적인 방식을 따라 동작하는 소프트웨어를 만드는데에 집중하는 것이 좋지 않을까요?

둘째, 유지보수 엔지니어들의 실수를 줄이기 위해서는 다른 방법을 제안할 수 있습니다. 예를 들어, 경로를 포함한 설정 파일 템플릿을 제공하고 설치 과정을 자동화하는 스크립트를 사용할 수 있습니다. 이렇게 하면 엔지니어들이 작업을 보다 효율적으로 수행할 수 있으며, 실수할 가능성도 줄일 수 있습니다. 설정 파일은 어차피 사이트별 데이터베이스 최적화 등을 위해 필요할테니, 디폴트값을 바이너리에 내장하기보다는 설정 파일 템플릿에 넣고 최대한 설치 과정을 자동화하는 쪽으로 노력을 기울이는 것이 장기적으로 득일 것 같습니다.

유지보수 과정은 제가 직접 겪은 것이 아니므로 이상은 원론적인 차원에서 말씀드린 것이니, 참고 의견 정도로 간주해주세요. 구현한 코드 자체에는 이견이 없고, 원래 방향대로 진행하기로 결정하신다면 머지해도 무방합니다.

2023-05-04 19:38 UTC, sehkone commented
@kimhanbeom @syncpark @msk 

제가 @syncpark 와 논의를 다각도에서 하였는데, @msk가 말씀하신 것처럼 설치 환경에 관련된 값이므로 소스에는 하드 코딩 하지 않기로 하였습니다. 다만, @syncpark 가 우려하시는 설치 과정에서의 실수는 그것대로 방지책이 필요한 것도 맞습니다. 그런데, 이는 경로 문제에 국한되는 것이 아니고 우리 소프트웨어 전체의 배포 및 설치 과정을 자동화 하는 것으로써 해결하는 것이 더 적절한 것으로 @syncpark 와 어제 의견을 정리하였고, 이를 위해 별도의 논의를 진행하도록 하겠습니다.

2023-05-04 19:43 UTC, msk commented
> ### 두번째 이슈
> 설정 파일의 위치는 디폴트 위치와 사용자 정의 위치의 2종류입니다.
> 
> 원격 설정할 때는 현재 사용중인 설정 파일 경로에 수정된 내용을 저장해야 하기 때문에 프로그램 시작할 때의 설정 파일 경로를 가지고 다니도록 수정한 내용입니다.

@sehkone 이 부분은 살려서 머지할 필요가 있습니다.

2023-05-04 20:16 UTC, sehkone commented
> > ### 두번째 이슈
> > 설정 파일의 위치는 디폴트 위치와 사용자 정의 위치의 2종류입니다.
> > 원격 설정할 때는 현재 사용중인 설정 파일 경로에 수정된 내용을 저장해야 하기 때문에 프로그램 시작할 때의 설정 파일 경로를 가지고 다니도록 수정한 내용입니다.
> 
> @sehkone 이 부분은 살려서 머지할 필요가 있습니다.

아 그렇습니다. @kimhanbeom, 반영해 주세요.

2023-05-10 08:47 UTC, syncpark approved these changes

2023-05-10 16:32 UTC, msk requested changes

2023-05-10 16:32 UTC, msk commented on src/settings.rs
> +    pub fn new() -> Result<(Self, String), ConfigError> {
설정파일 경로를 따로 리턴하는 것보다 `Settings` 안에 포함시키는 것이 나을 것 같습니다. 관례상 `new` 함수는 해당 `struct` 인스턴스를 리턴하는 것이 보통인데, 관례에서 벗어난 방식으로 사용하게 되면 코드를 읽는 사람 입장에서 별도로 기억할 것이 늘어나서 부담이 됩니다.

2023-05-10 16:32 UTC, msk commented on src/graphql/status.rs
> +        let cf_path = ctx.data::<String>()?;
settings.rs에서는 `cfg_path`란 이름을 쓰고 있으므로 여기도 같은 이름을 쓰는 것이 일관성 측면에서 바람직합니다.

2023-05-11 01:28 UTC, kimhanbeom commented
@msk 
해당 사항 수정 완료했습니다.

2023-05-11 16:08 UTC, msk approved these changes

2023-05-11 16:08 UTC, merged