Support mqtt protocol
aicers/giganto pull request #386
Opened 2023-05-08 05:27 UTC by BLYKIM

Close: #382

2023-05-08 05:28 UTC, BLYKIM commented
aicers/giganto-client#31

2023-05-08 07:50 UTC, syncpark requested changes

2023-05-08 07:50 UTC, syncpark commented on Cargo.toml
> +giganto-client = { git = "https://github.com/aicers/giganto-client.git", branch = "mqtt" }
aicers/giganto-client#31 merge되면 그 버전으로 수정해주세요.

2023-05-10 08:52 UTC, syncpark approved these changes

2023-05-10 08:53 UTC, merged