Add giganto clustering functionality
aicers/giganto pull request #408
Opened 2023-05-22 05:55 UTC by kimhanbeom

- Add giganto's peers options to config file.
- Accepts QUIC connections from giganto's peers.
- Add the capability to exchange source and peer address lists between peers of the giganto.
- Change giganto's execution command.

Closes: #325, #326

test10

2023-06-12 01:57 UTC, syncpark requested changes

2023-06-12 08:04 UTC, kimhanbeom commented
@syncpark 
해당 사항 수정 완료하였습니다.

2023-06-12 08:21 UTC, syncpark requested changes

2023-06-12 08:21 UTC, syncpark commented on src/peer.rs
> +async fn reqeust_init_info<T>(
스펠링 틀렸음. reqeust -> request

2023-06-12 08:21 UTC, syncpark commented on src/graphql/status.rs
> +        insert_toml_element("ingest_address", &mut doc, field.ingest_address);
한 번 이상 사용하는 문자열들은 별도의 const variable로 정의해서 잘못사용하는 것을 미리 방지하는게 좋겠습니다.

2023-06-12 09:07 UTC, kimhanbeom commented on src/peer.rs
> +async fn reqeust_init_info<T>(
스펠링 수정했습니다.

2023-06-12 09:07 UTC, kimhanbeom commented on src/graphql/status.rs
> +        insert_toml_element("ingest_address", &mut doc, field.ingest_address);
const로 변경 완료했습니다.

2023-06-12 09:11 UTC, syncpark approved these changes

2023-06-12 21:42 UTC, msk commented on README.md
> +giganto -c -p <path to config file>
설정파일에 peer_address가 있는지 없는지로 모드를 판별하는게 낫지 않을까요? 명령행 옵션을 추가하는 것이 어떤 장점이 있나요?

2023-06-13 00:53 UTC, kimhanbeom commented on README.md
> +giganto -c -p <path to config file>
자주 변경 하지는 않겠지만 매번 모드를 변경할 때 마다 설정파일을 수정하는 번거로움보다는 -c 옵션만 주면 간편하게 모드간의 변경이 쉬워서 명령행 옵션을 주었습니다.

2023-06-13 04:48 UTC, kimhanbeom commented on README.md
> +giganto -c -p <path to config file>
해당 사항 수정 완료했습니다.

2023-06-13 08:38 UTC, merged