Send Ack Message
aicers/giganto pull request #44
Opened 2022-09-05 00:41 UTC by kimhanbeom

Resolves: #30

2022-09-05 12:38 UTC, msk commented on src/ingestion.rs
> +const ACK_INTERVAL_TIME: u64 = 60 * 60;
`const`와 `struct` 사이에는 빈 줄을 하나 넣어주세요.

2022-09-05 23:54 UTC, kimhanbeom commented
해당 내용 수정 완료 했습니다.

2022-09-07 00:25 UTC, msk requested changes
1. 주기적으로 ACK를 보내는 루프와 통신할 때 lock을 사용하지 않고 channel 을 이용
2. ACK를 세는 것은 atomic variable을 이용

2022-09-07 06:31 UTC, kimhanbeom commented
해당 사항 수정 완료했습니다.

2022-09-07 18:40 UTC, msk approved these changes

2022-09-07 18:40 UTC, merged