Add Sources management logic
aicers/giganto pull request #59
Opened 2022-09-13 05:30 UTC by kimhanbeom

- Add Sources CF
- Add Channel/Spawn for update sources

Closes: #40

2022-09-13 22:33 UTC, msk requested changes

2022-09-13 22:33 UTC, msk commented on src/ingestion.rs
> +    pub static ref SOURCES: Mutex<HashMap<String, DateTime<Utc>>> = Mutex::new(HashMap::new());
`SOURCES`가 한 함수 내부에서밖에 안 쓰이는 것 같은데 `static`으로 할 필요가 있을까요?

2022-09-13 22:33 UTC, msk commented on src/ingestion.rs
> +                        let sources = SOURCES.lock().await.clone();
키만 사용할거면 키만 `clone`하는 것이 좋겠습니다.

2022-09-13 22:33 UTC, msk commented on src/ingestion.rs
> +                            SOURCES.lock().await.insert(source_key.to_string(),timestamp);
매크로 내부이다보니 rustfmt이 포맷을 안 고쳐주는데요, 수동으로라도 rustfmt이 포맷한 것과 동일하게 맞춰주세요. `,` 뒤에는 공백이 하나 필요합니다.

2022-09-13 23:18 UTC, kimhanbeom commented on src/ingestion.rs
> +    pub static ref SOURCES: Mutex<HashMap<String, DateTime<Utc>>> = Mutex::new(HashMap::new());
@msk 
추후 aicer web과 Reveiw를 통해 현재 접속중인 장비 목록을 가져올때 사용하기 위해  static으로 남겼습니다.

2022-09-14 02:30 UTC, kimhanbeom commented
해당 요청 사항 수정 완료했습니다.

2022-09-14 02:50 UTC, msk approved these changes

2022-09-14 02:50 UTC, merged