Fix retention method to apply rest cfs
aicers/giganto pull request #599
Opened 2023-11-14 05:33 UTC by BLYKIM

2023-11-19 23:58 UTC, sehkone commented
@BLYKIM 이슈를 등록하고 코딩을 하는 것이 바람직합니다만 부득이 이슈없이 PR을 할 때에는 PR에 자세하게 설명을 해 줘야 합니다. 

또한, PR을 올리고 reviewer를 정해주세요.

2023-11-21 01:24 UTC, syncpark requested changes

2023-11-21 01:24 UTC, syncpark commented on src/storage.rs
> +    (usage > 95, usage > 85)
95, 85는 별도의 Const 값으로 정의하는게 좋겠습니다.
info!() 로그 메시지에서도 그 Const 값으로 로그를 기록하도록 수정해주세요.

2023-11-21 04:19 UTC, syncpark commented
@BLYKIM 
RocksDB 관련 업데이트 내용중에 DeleteRange 기능 지원하는게 있던데 이걸 사용할 수 있는지 확인해주세요.

링크: https://github.com/facebook/rocksdb/wiki/RocksDB-Overview

2023-11-21 04:43 UTC, sophie-cluml commented on src/storage.rs
> +    pub fn retain_period_store(&self) -> Result<RetentionStores<()>> {
이번 개선으로 함수 위의 주석 상 괄호 부분을 지울 수 있게 된 것 같네요. 삭제 부탁드립니다.

2023-11-21 04:48 UTC, sophie-cluml commented
DeleteRange 외에도, `delete_file_in_range_cf` 가 더 성능관점 및 목적달성 관점에서 유리할 것으로 추측되어서 이것도 한 번 고려해주시면 좋을 것 같습니다.
현 PR 및 retain_periodically의 목적은 disk space의 확보로 이해하고 있습니다.
delete 및 delete_range는 delete명령을 memtable에 write -> 그 후 flush -> compaction 하는 방식으로 작동하지만, delete_file_in_range_cf는 sstfile을 delete하는 방식으로 작동합니다. retain_periodically는 상당한 양의 delete를 해야하는 작업을 수행하는 것으로 보여서, delete_file_in_range가 이득일 것 같아요. 관련 코드는 https://github.com/facebook/rocksdb/blob/336a74db604f10e1a4cc5d2e480fc8a895137f69/db/c.cc#L5454 이쪽입니다.

2023-11-21 05:40 UTC, BLYKIM commented
@syncpark @sophie-cluml 
* db의 많은 부분을 차지하는 standard_cf에 쓰이던 delete_range를 delete_file_in_range_cf로 변경하고 compact_range를 수행하는 것으로 수정하였습니다.
* non_standard_cf의 경우 키의 전체 범위를 특정할 수 없어 개별적으로 삭제하고 있으나 데이터 양이 상대적으로 적기 때문에 필요 범위만 보는 것으로 수정된 이후 큰 부담은 없을 것으로 보입니다.

2023-11-21 06:48 UTC, syncpark approved these changes

2023-11-21 07:30 UTC, sophie-cluml commented on src/storage.rs
> +                                store.db.compact_range_cf(store.cf, Some(&from), Some(&to));
요 두가지를 추가하신 이유가 있을것 같은데 이유를 알려주실 수 있을까요?
질문 배경은 제 생각엔 delete_file_in_range_cf를 도입한다면 memtable 및 WAL을 거치지 않기때문에 flush는 불필요할 것 같고, 이미 from ~ to 구간에 대해 데이터를 지워버렸기 때문에 그 구간에 대한 compact_range_cf를 호출하는 것은 실질적 액션이 취해지지 않는 call일 것 같아요.

2023-11-21 07:30 UTC, sophie-cluml commented on src/storage.rs
> +                let mut usage_flag = false;
usage_flag 는 `check_db_usage().await.0` 값으로 이해되는데요, 그 의미에 따라 is_over_usage_threshold 와 같은 명칭은 어떨지 의견드립니다. (채택하지 않으셔도 되는 단순 제안입니다.)

2023-11-21 07:38 UTC, BLYKIM commented on src/storage.rs
> +                                store.db.compact_range_cf(store.cf, Some(&from), Some(&to));
delete_file_in_range_cf를 하면 전체 범위의 데이터파일이 아닌 범위에 완전히 포함되는 sst파일만을 지운다고 상세 설명이 있어서 이후 compaction으로 나머지 데이터를 삭제할 수 있도록 하였습니다. 
각 delete와 compaction이 호출되기 이전에 펜딩되는 write가 있다면 디스크에 쓰여질 수 있도록 안정성을 위해 flush를 call하였습니다.

2023-11-21 07:39 UTC, BLYKIM commented on src/storage.rs
> +                let mut usage_flag = false;
이 retain작업이 usage에 의한 반복 작업인지, 단순 retention_period에 따른 작업인지에 대한 flag로 구분하기 위해 usage_flag로 작성하였습니다.

2023-11-21 07:42 UTC, BLYKIM commented on src/storage.rs
> +                let mut usage_flag = false;
USAGE_LOW에 도달할 때 까지 항상 true일 것이기 때문에 check_db_usage().await.0과는 차이가 있습니다..

2023-11-21 07:53 UTC, sophie-cluml commented on src/storage.rs
> +                                store.db.compact_range_cf(store.cf, Some(&from), Some(&to));
확인 감사합니다. from ~ to 범위를 완벽히 지우고 싶은 상황이라면, delete_file_in_range_cf가 누락한 부분에 대해 삭제가 일어나도록 delete_range를 써주는게 용도에 맞을 것 같아요. (compact_range_cf 는 삭제를 하지 않고 컴팩션만 하는 걸로 알고있어요.)

2023-11-21 08:04 UTC, BLYKIM commented on src/storage.rs
> +                                store.db.compact_range_cf(store.cf, Some(&from), Some(&to));
아 delete_range가 빠졌었네요. 범위 내 데이터를 확실히 지우기 위해 delete_range와 compact_range를 같이 써줬어야했는데 이 방법은 어떻게 생각하시나요?

2023-11-21 08:10 UTC, sophie-cluml commented on src/storage.rs
> +                                store.db.compact_range_cf(store.cf, Some(&from), Some(&to));
네 좋습니다!

2023-11-21 08:19 UTC, sophie-cluml commented on src/storage.rs
> +                let mut usage_flag = false;
네 변수명은 그대로 놔두셔도 좋습니다.
그런데 위에 달아주신 코멘트 중  `check_db_usage().await.0과는 차이가 있다`  지점에서 혹시나 하여서 말씀드리면, usage_flag가 value가 mutate 되는 지점은 딱 한번이고 실질적으로 `let usage_flag =  check_db_usage().await.0;` 과 완전히 동일한 것으로 보여요. 그런데 차이가 있다고 말씀주신 것은 혹시나... 아래쪽 loop 내에서 usage_flag 값의 mutation이 필요한 곳이 있었는데 누락된 것인가요? 그건 아니겠죠? 이것만 아니라면 resolve comment 처리하고 넘어가주시면 될거같습니다~!
```
                let mut usage_flag = false;
                if check_db_usage().await.0 {
                    info!("Disk usage is over {USAGE_THRESHOLD}%.");
                    retention_timestamp += ONE_DAY_TIMESTAMP_NANOS;
                    usage_flag = true;
                }
``

2023-11-21 08:38 UTC, BLYKIM commented on src/storage.rs
> +                let mut usage_flag = false;
말씀해주신대로 usage_flag는 실제로 변경되는 부분은 check_db_usage().await.0인 부분이 맞습니다.
usage가 THRESHOLD를 넘지 않는다면 false인 상태로 다음 loop를 돌지 않습니다.
usage가 THRESHOLD를 넘었을 때 true로 mutate되어 LOW보다 낮아질 때 까지 다음 loop 안에서 true이며, 다음 interval때 다시 false로 init됩니다.

다만 usage가 한번 THRESHOLD를 넘었었고, LOW까지 떨어지지 않았기때문에 loop를 돈다라는 의미에서 쓰여지는 것이라고 의도했기 때문에 결국 usage가 85 이하이고, usage_flag가 true이면 USAGE_LOW보다 낮아졌다는 로그와 함께 반복문을 빠져나오게 되므로 over threshold(usage > THRESHOLD) 와는 차이가 있다는 말이었습니다.

2023-11-21 09:51 UTC, sophie-cluml approved these changes
고생 많으셨습니다 🙇

2023-11-22 00:35 UTC, merged