Implement giganto cluster (part 2)
aicers/giganto pull request #628
Opened 2023-12-11 10:02 UTC by sophie-cluml

## Summary
- close #326 
- prev pr : https://github.com/aicers/giganto/pull/617

2023-12-11 11:21 UTC, sophie-cluml commented
@sehkone 현재 src/graphql.rs 에 쓰여진 cluster 관련 macro, function 등을 `cluster.rs` 파일로 옮기고자 하는데 의견 부탁드립니다. 패키지 구조도 일부 수정하려고 합니다. 현재 생각중인 방향은 다음과 같습니다.

<img width="794" alt="image" src="https://github.com/aicers/giganto/assets/148731228/c8140f61-6810-45a0-96f1-b4904bca33cf">

2023-12-11 23:39 UTC, sehkone commented
> @sehkone 현재 src/graphql.rs 에 쓰여진 cluster 관련 macro, function 등을 `cluster.rs` 파일로 옮기고자 하는데 의견 부탁드립니다. 패키지 구조도 일부 수정하려고 합니다. 현재 생각중인 방향은 다음과 같습니다.
> 

publish 쪽도 `graphql` 디렉토리에 들어가게 되나요? publish를 고려하면 graphql 보다 cluster가 더 상위의 개념인 것 같은데요.

2023-12-12 00:40 UTC, sehkone commented on CHANGELOG.md
> -[Unreleased]: https://github.com/aicers/giganto/compare/0.15.4...main
`[0.16.0]: <https://github.com/aicers/giganto/compare/0.15.4...0.16.0>`

이것을 추가해 주세요.

2023-12-12 06:22 UTC, sophie-cluml commented on CHANGELOG.md
> -[Unreleased]: https://github.com/aicers/giganto/compare/0.15.4...main
Done

2023-12-14 07:48 UTC, sehkone commented on src/graphql.rs
> +    edges.sort_by(|a, b| {
`sort_unstable_by`를 써도 될 것 같은데요.

2023-12-18 23:42 UTC, sehkone commented on src/graphql.rs
>      }
여기 `match`에 이은 `if let` 구문 전체는 `map_err` `?` `map` 등을 활용하면 `match`와 `it let`을 쓰지 않고 한 줄로 쓸 수 있습니다.

2023-12-18 23:43 UTC, sehkone commented on src/graphql/network.rs
이 파일은 라인 수가 너무 많은데, 몇 개의 파일로 나누는 게 좋겠습니다. 이번 PR에 포함하지 않고 이슈로 등록해서 다음에 할 수 있도록 해 주세요.

2023-12-19 02:29 UTC, sophie-cluml commented on src/graphql/network.rs
https://github.com/aicers/giganto/issues/631

2023-12-19 04:09 UTC, sophie-cluml commented on src/graphql.rs
>      }
async await 으로 인해서 한 줄로는 불가능하고 이 정도로 변경될 수 있을것 같습니다. 혹시 더 나은 방향이 있다면 알려주세요.

```rust
// 가능한 방향
    match resp.error_for_status() {
        Ok(resp_ok) => resp_ok
            .json::<GraphQlResponse<ResponseDataType>>()
            .await
            .map(|graphql_resp| response_to_result_converter(graphql_resp.data))
            .map_err(|_| Error::new("Peer giganto's response failed to deserialize.")),
        Err(e) => Err(Error::new(format!(
            "Peer giganto's response status is not success. {e}"
        ))),
    }

// 불가능한 방향
    resp.error_for_status()
        .map_err(|e| {
            Error::new(format!(
                "Peer giganto's response status is not success. {e}"
            ))
        })
        .and_then(|resp_ok| {
            resp_ok
                .json::<GraphQlResponse<ResponseDataType>>()
                .await
                .map_err(|_| Error::new("Peer giganto's response failed to deserialize."))
                .map(|graphql_resp| response_to_result_converter(graphql_resp.data))
        })
```

2023-12-19 04:24 UTC, sehkone commented on src/graphql.rs
>      }
```
resp.error_for_status()
   .map_err(|e| Error::new(format!("... ")))?
   .json::<GraphQlResponse<ResponseDataType>>()
   .await
   .map_err(|_| Error::new("..."))
   .map(|graphql_res| response_to_result_converter(graphql_res.data))
```

이렇게 하면 될 것 같은데 확인해 주세요.

2023-12-19 04:42 UTC, sehkone commented on src/graphql.rs
>      }
마지막 둘 `map_err`과 `map`은 순서를 바꾸는 게 맞는지는 적절하게 해 주세요.

2023-12-19 04:50 UTC, sophie-cluml commented on src/graphql.rs
>      }
오... 저기에 `?` 를 넣어버리면 해결되어버리는군요. 👍

2023-12-19 04:54 UTC, sophie-cluml commented on src/graphql.rs
>      }
<img width="496" alt="image" src="https://github.com/aicers/giganto/assets/148731228/9e497a44-b644-457a-a70a-b4a0bc2fb3a7">
완료입니다.

2023-12-19 05:54 UTC, sehkone commented on src/peer.rs
> +const PEER_VERSION_REQ: &str = ">=0.16.0,<0.17.0";
여기에 alpha를 써야하지 않나요?

2023-12-19 05:54 UTC, sehkone commented on src/peer.rs
> +    const PROTOCOL_VERSION: &str = "0.16.0";
여기도 alpha를?

2023-12-19 06:31 UTC, sophie-cluml commented on src/peer.rs
> +const PEER_VERSION_REQ: &str = ">=0.16.0,<0.17.0";
Thank you, done

2023-12-19 06:31 UTC, sophie-cluml commented on src/peer.rs
> +    const PROTOCOL_VERSION: &str = "0.16.0";
Thank you, done

2023-12-19 06:31 UTC, sophie-cluml commented on src/graphql.rs
>      }
done

2023-12-19 06:37 UTC, sehkone commented on src/peer.rs
> +const PEER_VERSION_REQ: &str = ">=0.16.0-alpha,<0.17.0";
`alpha.1` 이라고 해야되는 것 아닌가요?

2023-12-19 06:46 UTC, sophie-cluml commented on src/peer.rs
> +const PEER_VERSION_REQ: &str = ">=0.16.0-alpha,<0.17.0";
👍  Done

2023-12-19 06:47 UTC, sehkone approved these changes

2023-12-20 02:29 UTC, syncpark requested changes

2023-12-20 02:29 UTC, syncpark commented on src/graphql/network.rs
> +#[graphql_client_type(names = [smtp_raw_events::SmtpRawEventsSmtpRawEventsEdgesNode, ])]
SMTP에서는 `network_raw_events::NetworkRawEventsNetworkRawEventsEdgesNodeOnSmtpRawEvent`가 빠진것 같은데요.

2023-12-20 02:29 UTC, syncpark commented on src/graphql/network.rs
> +        match node {
SMTP 프로토콜이 빠진것 같습니다.

2023-12-20 02:29 UTC, syncpark commented on src/graphql/network.rs
> +                get_peekable_iter(&db.conn_store()?, &filter, &after, &before, first, last)?;
smtp 프로토콜이 일부러 빼신건가요?

2023-12-20 03:47 UTC, sophie-cluml commented on src/graphql/network.rs
> +#[graphql_client_type(names = [smtp_raw_events::SmtpRawEventsSmtpRawEventsEdgesNode, ])]
union 쿼리가 기존부터 smtp를 핸들링하고 있지 않습니다. 그런데, 기존에 핸들링 하지 않고 있던 상황이 의도된 것이 아니라 누락이라면  cluster와 별개 사안으로 smtp에 대한 핸들링을 추가가 필요하다고 보입니다. 이하 SMTP에 대한 다른 코멘트도 동일한 포인트로 파악되네요.

2023-12-20 03:56 UTC, sophie-cluml commented on src/graphql/network.rs
> +#[graphql_client_type(names = [smtp_raw_events::SmtpRawEventsSmtpRawEventsEdgesNode, ])]
누락이라고 판단되시면 알려주세요 별도 issue 작성하려고 합니다.

2023-12-20 04:58 UTC, syncpark commented on src/graphql/network.rs
> +#[graphql_client_type(names = [smtp_raw_events::SmtpRawEventsSmtpRawEventsEdgesNode, ])]
@MW-Kim @kimhanbeom @BLYKIM
혹시 GraphQL query에서 SMTP를 제외했던 이유가 있을까요? 개인정보나 그런 비슷한 이유로?

schema.graphql 파일을 확인해보니 확실히 SMTP가 빠져있네요.
```graphql
wEvents =
    ConnRawEvent
  | DnsRawEvent
  | HttpRawEvent
  | RdpRawEvent
  | NtlmRawEvent
  | KerberosRawEvent
  | SshRawEvent
  | DceRpcRawEvent
  | FtpRawEvent
  | MqttRawEvent
  | LdapRawEvent
  | TlsRawEvent
  | SmbRawEvent
  | NfsRawEvent
```

2023-12-20 05:54 UTC, syncpark commented on src/graphql/network.rs
> +#[graphql_client_type(names = [smtp_raw_events::SmtpRawEventsSmtpRawEventsEdgesNode, ])]
@David @MW-Kim 과 얘기해봤는데 넣는 게 좋다는 걸로 합의 봤습니다. 말씀처럼 별도 이슈로 정리하는게 좋겠습니다.

2023-12-20 07:25 UTC, sophie-cluml commented on src/graphql/network.rs
> +#[graphql_client_type(names = [smtp_raw_events::SmtpRawEventsSmtpRawEventsEdgesNode, ])]
https://github.com/aicers/giganto/issues/633 등록되었습니다.

2023-12-26 06:29 UTC, sehkone commented
@syncpark Review 마무리 부탁드려요

2023-12-26 08:04 UTC, syncpark approved these changes

2023-12-26 08:08 UTC, merged