[WIP] Sophie/giganto cluster publish meesage
aicers/giganto pull request #630
Opened 2023-12-19 02:05 UTC by sophie-cluml

prev PR : https://github.com/aicers/giganto/pull/628

2024-01-02 01:40 UTC, sehkone commented on src/publish.rs
> +                    "Niether current nor peer gigantos are in charge of requested pcap source {}",
typo 수정해 주세요

2024-01-02 01:47 UTC, sehkone commented on src/publish.rs
> +// }
불필요한 주석은 삭제해 주세요.

2024-01-02 01:47 UTC, sehkone commented on src/publish.rs
> +    // done pita
불필요한 주석은 삭제해 주세요.

2024-01-02 03:16 UTC, sehkone commented on CHANGELOG.md
> +- Added giganto cluster support for GraphQL and publish message requests.
이 내용이 Added에 들어가면 하위 호환성에 문제가 없어 보입니다. Breaking change는 Changed에 적는 것이 바람직합니다.

2024-01-02 03:16 UTC, sehkone commented on CHANGELOG.md
> +- Added giganto cluster support for GraphQL and publish message requests.
다른 사항들도 검토해서 Changed에 들어가야할 것은 옮겨 주세요.

2024-01-02 03:18 UTC, sehkone commented on src/ingest/tests.rs
>  const PROTOCOL_VERSION: &str = "0.15.2";
버전이 맞나요?

2024-01-02 03:27 UTC, sehkone commented on src/publish.rs
> +    // done pita
이것도 불필요한 주석?

2024-01-02 04:54 UTC, sophie-cluml commented on src/ingest/tests.rs
>  const PROTOCOL_VERSION: &str = "0.15.2";
cluster 변경으로 인해 영향 받는 것은 publish, peer 여서 ingest protocol 버전은 0.15.2 로 유지해도 정상동작 하는 게 맞아서 이대로 놔두어도 괜찮습니다.

2024-01-02 04:55 UTC, sophie-cluml commented on CHANGELOG.md
> +- Added giganto cluster support for GraphQL and publish message requests.
done

2024-01-02 06:31 UTC, sehkone approved these changes

2024-01-02 08:04 UTC, syncpark requested changes

2024-01-02 09:19 UTC, sophie-cluml commented on src/publish.rs
> +    for req_input in req_inputs {
> 1. requested source가 My Giganto나 Remote Giganto 모두에서 없을 가능성도 있을까요?

네 모두 없을 가능성은 있습니다. 그런 경우, 기존에 giganto가 1대이던 과거방식과 마찬가지로 동작합니다. 예를 들어서, giganto가 과거 1대였을 때 기준, 전혀 모르는 source인 `some_unknown_source` 에 대한 "raw_events" 요청이 들어온 경우 giganto는 다음과 같은 데이터를 reconverge 또는 hog에게 전달합니다.
```
    send_range_data::<T>(send, None).await?;
    send.finish().await?;
```

이번에 변경된 클러스터 상황에서도, `some_unknown_source`가 들어오면, my giganto `handle_by_current_giganto.is_empty()` 에서 아무런 데이터도 전달하지 않게 되고, peer gigantos 는 process_raw_event_in_peer_gigantos 에 진입하기는 하지만, `some_unknown_source` 와 매핑되는 peer giganto 가 없기 때문에 해당 `some_unknown_source` 에 대해 다른 giganto들에게 질의하지 않게 됩니다.



> 2. Remote Giganto에게 request를 던질 때 Broadcasting처럼 던지는 건가요? 아니면 특정 Giganto를 콕 찍어서 보낼 수 있나요?

특정 Giganto를 콕 찍어서 보내고 있습니다. `process_raw_events` , `process_range_data`, `process_pcap_extract` 모두 콕 찍는 방식입니다. 다만, hog나 reconverge가 요청하는 데이터가 모든 giganto에 걸쳐 존재하는 경우라면 마치 브로드캐스팅하는 것과 유사한 상황이 연출될 수도 있습니다. 



> 3. Giganto cluster 사이에 주고받는 메시지를 최적화할 수 있지 않을까요?

네 동의합니다.  chunk 단위로 주고받는 방법이라던가, giganto가 중간에 relay하는 것을 없애고 그냥 직접 데이터가 존재하는 giganto가 어떤 giganto인지 알려주는 방법 등을 고려해볼 수 있을 것 같습니다. (현 pr에서는 기존의 함수를 그대로 활용하여 건 바이 건으로 현재 메시지가 주고 받아지고 있습니다.) 다른 최적화 아이디어도 있을 것 같은데, 알려주세요~! 


> 4. 자신에게 없는 Source에 대한 요청을 받았을 때 다른 Giganto에게 던지게 되는데, 이렇게 핑퐁하다가 무한루프에 빠지진 않겠지요?

앞서 1번에서는 `process_raw_events` 만을 예로 들었으나, `process_range_data`, `process_pcap_extract` 도 마찬가지로 `some_unknown_source`에 대해서 giganto 가 1대 였을 때와 동일한 동작을 할 것이라서 무한루프 리스크는 적절히 방어했다고 보고 있습니다.

2024-01-07 23:39 UTC, sehkone commented
@syncpark 리뷰 다 하셨나요?

2024-01-08 03:31 UTC, syncpark approved these changes

2024-01-08 03:31 UTC, syncpark commented
> @syncpark 리뷰 다 하셨나요?

예. 리뷰 끝났습니다.

2024-01-08 06:32 UTC, sophie-cluml commented on CHANGELOG.md
> +## [0.16.0] - 2024-01-08
rebase 하면서 일자를 변경했습니다.

2024-01-08 06:56 UTC, sophie-cluml commented on src/publish.rs
> +                        error!(LogLocation::Both, "Peer giganto's server name cannot be identitified. addr: {peer_addr}, source: {}", filter.source);
log-broker 가 적용된 base branch에 발맞추어 로깅을 log-broker에 맞게 업데이트 했습니다.

2024-01-08 09:56 UTC, sehkone approved these changes

2024-01-08 09:57 UTC, merged