Support giganto-client 0.17.0
aicers/giganto pull request #743
Opened 2024-05-21 08:52 UTC by kimhanbeom

- Update `quinn`/`rustls` version.
- Fixed code and structures based on changes to the `conn`/`http`/`smtp`/`ntlm` /`ssh`/`tls` protocols field.
- Update the compatibility version of the quic communication modules.
- Update the compatibility version for migration.
- Added migration function `migrate_0_19_to_0_21_0_alpha_1`.

Close: #730

2024-05-22 01:22 UTC, sophie-cluml commented on src/storage/migration/migration_structures.rs
> +pub struct NewHttpV19ToV21A1 {
이 마이그레이션은 giganto-client에 의해 발생한 것이므로 giganto-client의 `Http` 를 쓰는 게 낫지 않을까요?

2024-05-22 01:22 UTC, sophie-cluml commented on src/storage/migration/migration_structures.rs
> +impl From<NewHttpV10ToV12> for NewHttpV19ToV21A1 {
Http와 관련 struct가 `OldHttpV10ToV12`, `NewHttpV10ToV12`, `NewHttpV19ToV21A1` 존재하는데 만약 앞으로 더 추가된다면 이름 앞에 항상 new 가 추가되는 규칙이 있는 것으로 예상되어요. 스트럭트 간의 관계를 나타내는 old, new 단어를 스트럭트 명칭에 사용하는 대신, 스트럭트 그 자체를 나타낼 수 있는 다음과 같은 접근은  어떨까요?

`OldHttpV10ToV12` -> `HttpBeforeV12`
`NewHttpV10ToV12` -> `HttpFromV12BeforeV21`
`NewHttpV19ToV21A1` -> giganto-client의 `Http`를 그대로 사용하거나, alias 해서 `HttpFromV21`

2024-05-22 01:29 UTC, kimhanbeom commented on src/storage/migration/migration_structures.rs
> +pub struct NewHttpV19ToV21A1 {
추후 giganto-client version 업데이트시 http 구조체의 필드가 추가/삭제될 경우, 그때 해당 migration을 위한 http 구조체를 정의해야하는데 그럴 필요 없도록 미리 정의해두었습니다.

2024-05-22 07:10 UTC, syncpark requested changes

2024-05-22 07:10 UTC, syncpark commented on src/storage/migration.rs
> +
이번 수정된 내용으로 DB 마이그레이션 작업은 아마도 시간이 매우 많이 걸릴 것 같습니다.
지켜보는 엔지니어를 위해서 개별 DB 마이그레이션 시작과 종료 시점에 로그 한 줄씩 추가하는게 어떨까요?

몇 시간 이상 걸릴 수도 있는 작업일테니 로그를 보면서 진행 상태를 확인할 수 있으면 좋겠습니다.

2024-05-22 07:17 UTC, kimhanbeom commented on src/storage/migration.rs
> +
기존 migration에서 개별 시작 로그는 출력해주고 있으니 개별 종료시의 로그만 추가하도록 하겠습니다.

2024-05-23 01:17 UTC, kimhanbeom commented on src/storage/migration/migration_structures.rs
> +impl From<NewHttpV10ToV12> for NewHttpV19ToV21A1 {
done

2024-05-23 01:17 UTC, kimhanbeom commented on src/storage/migration.rs
> +
done

2024-05-23 04:19 UTC, sophie-cluml commented on src/storage/migration/migration_structures.rs
> +pub struct NewHttpV19ToV21A1 {
추후 필요성이 있다는 점을 고려하여 이미 코드가 작성되었으니 그대로 두는 것도 일리가 있다고 생각합니다. 그럼에도 불구하고 giganto에서 별개의 구조체를 정의하는 것보다는 giganto-client의 `Http` 구조체를 사용하는 것이 안전성 관점에서 이득이 있는 것 같아요. 추후 giganto-client 버전에서 `Http` 구조체가 변경된 상황을 가정해보면,
- giganto가 giganto-client의 `Http`를 사용하는 경우, migration.rs의 코드 자체가 컴파일이 되지 않으므로, migration 코드를 작성하는 것을 놓칠 수가 없습니다.
- giganto가 giganto에서 직접 `HttpFromV21` 를 정의하여 사용하는 경우, migrtaion.rs 코드 컴파일이 정상적으로 되므로, migration 코드를 작성하는 것을 만에 하나 놓칠 수 있습니다. (놓침 여부는 역량, 컨디션, 운 등의 영향을 받을 것 같아요)

migration을 놓칠 때 발생하는 문제는 큰 문제로 이어질 가능성이 높기 때문에, giganto-client의 `Http`를 사용하는 것이 이득이 더 크다고 생각합니다. 추후 필요할 때 그 때 작성하는 것이 적절한 시점일 것 같아요.

한편, 최초 코멘트를 조금 더 정확히 부연해보면, giganto-client의 `ingest::network::Http`는 giganto 에서 DB의 Http 테이블 스키마로 사용되고 있는데, migration 목적은 스키마 변경이므로, 신규 DB 스키마에 해당하는 바로 그 `Http` 를 사용하는 게 좋을 것 같다는 뜻이었습니다. 마이그레이션에서는 통신이 아니라 DB 스키마가 관심사이므로, 코드 상에서는 `use ingest::network::Http`를 직접 쓰는 것보다 `use crate::storage::Http`로 접근하는 것이 더 낫다고 생각해요.

2024-05-23 04:46 UTC, kimhanbeom commented on src/storage/migration/migration_structures.rs
> +pub struct NewHttpV19ToV21A1 {
done

2024-05-23 08:33 UTC, kimhanbeom commented on src/storage/migration/migration_structures.rs
> +pub struct NewHttpV19ToV21A1 {
해당 내용 적용 완료했습니다.

2024-05-23 09:36 UTC, sophie-cluml approved these changes
LGTM

2024-05-23 23:48 UTC, syncpark approved these changes

2024-05-24 00:33 UTC, merged