Release 0.21.0
aicers/giganto pull request #837
Opened 2024-09-23 10:06 UTC by sophie-cluml

related to #823
close #836 

This PR is related to two issues, since #836 and #823 cannot be easily split into separate PRs, mainly because #836 could be considered as a subset task of #823.

2024-09-23 16:40 UTC, msk commented
@sophie-cluml, thanks for working on the new release of Giganto (and the migration optimization—that was a good catch!). I noticed that this PR is using a version of `giganto-client` that's a few commits behind the latest release (0.20.0). Since @petabi plans to migrate its applications to `giganto-client` 0.20.0, I'm concerned about potential compatibility issues with Giganto 0.21.0. Would it be possible to update the `giganto-client` dependency in this PR to the latest release to ensure compatibility?

2024-09-24 02:17 UTC, kimhanbeom commented
https://github.com/aicers/giganto/blob/100798454e55fc4c77304167962e883fac136113/src/storage/migration.rs#L436-L438

Could you please change it to `migrate_0_19_to_0_21_0`?

2024-09-24 02:20 UTC, kimhanbeom requested changes

2024-09-24 02:20 UTC, kimhanbeom commented on src/storage/migration.rs
>          //migration 0.19.0 to 0.21.0-alpha.1
```suggestion
        //migration 0.19.0 to 0.21.0
```

2024-09-24 02:48 UTC, sophie-cluml commented on src/storage/migration.rs
>          //migration 0.19.0 to 0.21.0-alpha.1
Done

2024-09-24 02:51 UTC, kimhanbeom approved these changes

2024-09-24 03:30 UTC, merged